import dotenv from 'dotenv';
dotenv.config();

export const {
  PORT,
  NODE_ENV,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_PRIVATE_KEY,
  REDIS_URL,
  SUPABASE_DATABASE_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  JWT_SECRET,
  JWT_REFRESH_SECRET,
} = process.env;
